---
- name: Disable VGA for GPU
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/vfio.conf
    line: "options vfio-pci ids={{ proxmox_pci_passthrough_gpu_ids }} disable_vga=1"
    create: true
  when: proxmox_pci_passthrough_gpu_ids is defined
  notify:
    - Update initramfs
    - Reboot
