---
- name: Blacklist drivers
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "blacklist {{ item }}"
    create: true
    mode: u=rw,g=r,o=r
  loop: "{{ proxmox_pci_passthrough_blacklist_drivers }}"
  notify:
    - Update initramfs
    - Reboot
