---
- name: Validate boot_type var
  ansible.builtin.fail:
    msg: The `proxmox_pci_passthrough_boot_type` needs to be either "grub" or "systemd"
  when:
    - proxmox_pci_passthrough_boot_type != "grub"
    - proxmox_pci_passthrough_boot_type != "systemd"

- name: Configure GRUB cmdline
  include_tasks: "enable-iommu-grub.yml"
  when: proxmox_pci_passthrough_boot_type == "grub"

- name: Configure systemd cmdline
  include_tasks: "enable-iommu-systemd.yml"
  when: proxmox_pci_passthrough_boot_type == "systemd"
